### ISSUE TITLE
Secure response when Jsonfield include default attribute

### ISSUE THREAD

**Issue by rubenvos** [antonioIrizar/django-check-migration-wtf#71]
When you include 'default' attribute into JsonField module return 'secure migration' but really it is not secure migration.

Ex: Django field definition.

`data = models.JSONField(default=dict, blank=True, null=True)`

Sql migrate result

`ALTER TABLE "accounts_customer" ADD COLUMN "data" jsonb DEFAULT '{}' NULL;
ALTER TABLE "accounts_customer" ALTER COLUMN "data" DROP DEFAULT;
COMMIT;`

**Comment by antonioIrizar** [comment]
It is worrking correctly. This addives onlye execute when postgreSQL version is low than 1. Explain about it https://www.dbi-services.com/blog/postgresql-11-instant-add-column-with-a-non-null-default-value/
